name: Run single PHP file

on:
  push:
    branches:
      - main # Możesz zmienić na inną gałąź

jobs:
  run-php-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Możesz zmienić na inną wersję

      - name: Run PHP file
        run: php index.php
